
#To enable a workflow to be triggered manually, you need to configure the workflow_dispatch event.  -https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch

#by default, jobs will run in parallel, which is not desired while setting up a dev-qa-uat-prod structure. to run jobs sequentially, use job needs.
#https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow
#https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds

name: learn-github-actions
on: [workflow_dispatch] #[] denotes a list so multiple values can be run such as push[0]
jobs:
  DEV:
    runs-on: ubuntu-latest #github provides its own runner (running on ubuntu)
    steps:
      - run: echo Hello
  QA:
    runs-on: ubuntu-latest #github provides its own runner (running on ubuntu)
    needs: #to setup sequential execution. will run after provided value
      - DEV
    steps:
      - run: echo Hello
  UAT:
    runs-on: ubuntu-latest #github provides its own runner (running on ubuntu)
    needs: #to setup sequential execution. will run after provided value
      - QA
    steps:
      - run: echo Hello
  PROD:
    runs-on: ubuntu-latest #github provides its own runner (running on ubuntu)
    needs: #to setup sequential execution. will run after provided value
      - UAT
    steps:
      - run: echo Hello